.travis.yml

Merge "build and push docker image" stage and "deploy" stage

---

Gemfile
Gemfile.lock
app/assets/javascripts/root.coffee
app/controllers/users_controller.rb
app/mailers/user_mailer.rb
app/models/user.rb
app/views/user_mailer/email_confirmation.text.erb
config/environments/alpha.rb
config/environments/development.rb
config/initializers/locale.rb
config/locales/controllers/en.yml
config/locales/controllers/ko.yml
config/locales/en.yml
config/locales/ko.yml
config/locales/mailers/en.yml
config/locales/mailers/ko.yml
config/routes.rb
db/migrate/20180630140522_create_users.rb
db/migrate/20180702020425_add_default_to_confirm_token.rb
db/schema.rb
lib/tasks/auto_annotate_models.rake
test/controllers/root_controller_test.rb
test/controllers/users_controller_test.rb
test/fixtures/users.yml
test/mailers/previews/user_mailer_preview.rb
test/mailers/user_mailer_test.rb
test/models/user_test.rb

Email confirmation

---

LICENSE

Add the LICENSE

---

.gitignore
.travis.yml
README.md
package.json
test/frontend/elm/Test/Wallet.elm
test/frontend/elm/elm-package.json
yarn.lock

Also, add a test of Wallet module.

Set elm test environment.

---

app/frontend/src/stylesheets/action-view-container.scss
app/frontend/src/stylesheets/base.scss
app/frontend/src/stylesheets/button.scss
app/frontend/src/stylesheets/join.scss
app/frontend/src/stylesheets/layout.scss
app/frontend/src/stylesheets/main.scss
app/frontend/src/stylesheets/sidebar.scss

1. elm package html 구조에 따른 클래스 상속자 변경.
2. image embedding path를 절대값으로 변경.

changed layout styling

---

app/frontend/src/elm/Main.elm
app/frontend/src/elm/Response.elm
app/frontend/src/elm/Sidebar.elm
app/frontend/src/elm/Translation.elm
app/frontend/src/elm/Util/WalletDecoder.elm
app/frontend/src/js/index.js
app/frontend/src/js/state.js
app/frontend/src/js/wallet.js
test/frontend/elm/Test/Sidebar.elm

Also, upgrade scatter interaction.

Construct overall view.

---

app/frontend/src/stylesheets/action-view-container.scss
app/frontend/src/stylesheets/sidebar.scss

demo : https://jdrunken.github.io/eoshub-ui/transfer.html

changed config button play / transfer page notification interaction time adj

---

app/frontend/src/elm/Data/Account.elm
app/frontend/src/elm/Header.elm
test/frontend/elm/Test/Header.elm

Separate Account Type and Decoder from Header.elm

---

app/frontend/src/stylesheets/action-view-transfer.scss
app/frontend/src/stylesheets/sidebar.scss

change visual object :: svg > only css

make interaction sidebar folding button 

---

app/frontend/src/image/icon-check-circle.svg
app/frontend/src/stylesheets/join.scss

계정생성 페이지를 새롭게 했습니다.
https://jdrunken.github.io/eoshub-ui/join_make_account_step1.html

renew make accout page all.

---

app/frontend/src/stylesheets/join.scss

image element 모두 제거해주시고, 스타일시트 머징하면 바로 적용됩니다.

remove image element in html for set embedding path

---

app/frontend/src/elm/Page/Account/ConfirmEmail.elm
test/frontend/elm/Test/Page/Account/ConfirmEmail.elm

이메일 형식을 검증하는  로직과 이메일 인증 요청을 서버에 보낸 후의 결과를 표시하는 로직을 정리하였습니다.

Email validation

---

app/frontend/src/stylesheets/button.scss

그림에 이미지가 어색하게 보이던 문제를 해결했습니다.
https://jdrunken.github.io/eoshub-ui/transfer.html

remove border-width

---

app/frontend/src/elm/Main.elm
app/frontend/src/elm/Page/Account/ConfirmEmail.elm
app/frontend/src/elm/Page/Account/Create.elm
app/frontend/src/elm/Page/Account/CreateKeys.elm
app/frontend/src/elm/Page/Account/Created.elm
app/frontend/src/elm/Page/Account/EmailConfirmed.elm

이미지 어셋 링크에 해시값이 포함되는 처리를 해야하는데
진훈님이 일단 간단한 해결책으로 이미지를 css에 포함시켜 주셨습니다.

Remove image tag (images are embed in css)

---

app/frontend/src/stylesheets/action-view-search.scss

레이아웃 변화(width)에 따라 스타일이 조금 변화될 여지는 있습니다만, html model은 변동이 없을겁니다 :)
https://jdrunken.github.io/eoshub-ui/public-key.html

add search page - public key

---

app/frontend/src/image/icon-clipboard.svg
app/frontend/src/image/icon-close-black.svg
app/frontend/src/stylesheets/action-view-search.scss
app/frontend/src/stylesheets/common.scss

테이블에 메모를 볼 수 있는 엘리먼트 추가되었습니다.
https://jdrunken.github.io/eoshub-ui/search.html

memo button/layer added in search page table

---

app/frontend/src/stylesheets/base.scss

anchor element의 기본 커서를 defalut에서 pointer로 변경합니다.
바로 머징 후 branch 삭제하겠습니다.

make cursor default shape for null href

---

app/frontend/src/elm/Component/Account/AccountComponent.elm
app/frontend/src/elm/Component/Account/Page/ConfirmEmail.elm
app/frontend/src/elm/Component/Account/Page/Create.elm
app/frontend/src/elm/Component/Account/Page/CreateKeys.elm
app/frontend/src/elm/Component/Account/Page/Created.elm
app/frontend/src/elm/Component/Account/Page/EmailConfirmFailure.elm
app/frontend/src/elm/Component/Account/Page/EmailConfirmed.elm
app/frontend/src/elm/Component/Main/MainComponent.elm
app/frontend/src/elm/Component/Main/Page/Index.elm
app/frontend/src/elm/Component/Main/Page/NotFound.elm
app/frontend/src/elm/Component/Main/Page/Search.elm
app/frontend/src/elm/Component/Main/Page/SearchKey.elm
app/frontend/src/elm/Component/Main/Page/Transfer.elm
app/frontend/src/elm/Component/Main/Page/Voting.elm
app/frontend/src/elm/Component/Main/Sidebar.elm
app/frontend/src/elm/Main.elm
test/frontend/elm/Test/Component/Account/AccountComponent.elm
test/frontend/elm/Test/Component/Account/Page/ConfirmEmail.elm
test/frontend/elm/Test/Component/Account/Page/Create.elm
test/frontend/elm/Test/Component/Main/MainComponent.elm
test/frontend/elm/Test/Component/Main/Page/Search.elm
test/frontend/elm/Test/Component/Main/Page/Transfer.elm
test/frontend/elm/Test/Component/Main/Sidebar.elm

Component.Main에 Page(subpages), MainComponent, Sidebar
Component.Account에 AccountComponent, Page(subpages) 담도록 디렉토리 구조 수정했습니다.

Refactor directory structure.

---

app/frontend/src/elm/Component/Main/Page/Search.elm
app/frontend/src/elm/Component/Main/Sidebar.elm
app/frontend/src/elm/Data/Account.elm
app/frontend/src/elm/Util/HttpRequest.elm
app/frontend/src/elm/Util/Urls.elm
test/frontend/elm/Test/Component/Main/Sidebar.elm
test/frontend/elm/Test/Data/Account.elm
test/frontend/elm/Test/Util/HttpRequest.elm

Also, do some refactoring and bug fixing.

Implement account info fetching on sidebar.

---

app/frontend/src/stylesheets/join.scss

상단 circle의 위치를 고정시키고 글자 길이에 line이 영향받지 않도록 처리함
@sinhyeok-cp  alpha branch에 머징시켜 두겠습니다. 체리픽 하셔서 가져다 쓰시면 됩니다.

fix nav interface for join process

---

app/frontend/src/elm/Component/Main/MainComponent.elm
app/frontend/src/elm/Component/Main/Page/Transfer.elm
app/frontend/src/elm/Translation.elm
test/frontend/elm/Test/Component/Main/Page/Transfer.elm
test/frontend/elm/Test/Translation.elm

Also, modify some chinese translations following 
https://docs.google.com/spreadsheets/d/1EoE0L-totuVAYZssTQfvUMoBZCjv6AqpEUNj1xCpSg0/edit#gid=1351809970
Enhance validation tests.

Implement Transfer amount validation.

---

app/frontend/src/elm/Component/Main/MainComponent.elm
app/frontend/src/elm/Component/Main/Page/Search.elm
app/frontend/src/elm/Data/Action.elm
app/frontend/src/elm/Main.elm
app/frontend/src/elm/Util/Urls.elm

각 액션을 엘름 모델로 디코딩하는 /Data/Action.elm 입니다.

Add ActionDecoder

---

app/frontend/src/elm/Component/Main/Page/Search.elm

category select 기능 추가하였습니다. 현재 <button> 형태는 리뉴얼을 통해 <select>로 변경될 예정입니다.

Implement category select

---

app/controllers/root_controller.rb
app/views/layouts/root.html.erb

to prevent eoshub pages are affected by admin layout changes

Separate root layout

---

app/frontend/src/elm/Component/Main/MainComponent.elm
app/frontend/src/elm/Component/Main/Sidebar.elm
app/frontend/src/elm/Main.elm
app/frontend/src/js/index.js

1. 계정 생성 페이지에서 백버튼을 눌러서 메인 페이지로 돌아갔을때 사이드바에 로딩 표시가 유지되는 문제 해결
2. 메인 페이지 최초 로딩시 initCmd를 통해 wallet status check하도록 구조 변경

Resolve the sidebar loading problem

---

.gitmodules
.travis.yml

Add private repo as submodule.

Import trading view chart library.

---

.babelrc
.gitmodules
.travis.yml

To resolve travis build issue, try changing protocol.
Also, move submodule directory.

Change address protocol from git to https on submodules.

---

app/frontend/src/image/icon-menu-toggle.svg
app/frontend/src/stylesheets/aside.scss
app/frontend/src/stylesheets/base.scss
app/frontend/src/stylesheets/env.scss
app/frontend/src/stylesheets/footer.scss
app/frontend/src/stylesheets/layout.scss
app/frontend/src/stylesheets/main.search.scss
app/frontend/src/stylesheets/main.transfer.scss
app/frontend/src/stylesheets/nav.scss

@basakkang 
검색 페이지의 테이블 처리 되어있습니다.
https://jdrunken.github.io/ui.eoshub/search.html
@Heejaejoo 
global nav bar에 인터랙션이 추가되었습니다.
현재 보고있는 페이지의 메뉴에 `viewing` 추가 부탁드립니다.

design washing / modify to search page table / gnb interaction added

---

app/frontend/src/stylesheets/layout.scss

@Heejaejoo 
토큰 리스트 입력필드의 돋보기 그림을 지정하는 클래스를 추가 부여하였습니다.
elm에서 class 지정 부탁드립니다.  `.search_token` 입니다.

change input icon object inside popup

---

.travis.yml

https://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package

Specify python version to resolve build error

---

.travis.yml

Remove --user option

---

db/migrate/20180910110901_add_initial_price_history_intvls.rb
db/schema.rb
db/seeds.rb

Instead of using seed data with db:seeds, make it as migration.

Implement seed data migration.

---

config/urls.yml
deploy/alpha/supervisord.conf

Also, add user to sidekiq job on supervisord.

Fix redis url.

---

app/frontend/src/stylesheets/main.resource.scss

https://chainpartners.slack.com/archives/GBL7V5U14/p1536653076000100

delete input decoration (by @bassakang)

---

app/frontend/src/elm/Component/Main/MainComponent.elm
app/frontend/src/elm/Component/Main/Page/Rammarket.elm
app/frontend/src/elm/Component/Main/Page/Transfer.elm
app/frontend/src/elm/Component/Main/Sidebar.elm
app/frontend/src/elm/Data/Table.elm
app/frontend/src/elm/Util/Formatter.elm
app/frontend/src/elm/Util/HttpRequest.elm
test/frontend/elm/Test/Component/Main/Page/Rammarket.elm
test/frontend/elm/Test/Util/Formatter.elm

Note that the polling interval is set to 2 seconds.
Also, fix bugs regarding action list ordering.

Implement polling on ram market page.

---

app/frontend/src/stylesheets/main.resource.scss

for @basakkang 
```
@진훈 언스테이크 페이지에서 <p class=“validate description”>CPU는 최소 0.7 EOS, NET은 최소 0.3 EOS 이상 스테이킹 하세요.</p> class에 true/false들어가면 색 바뀌도록 변경 부탁드립니다.
```

higher to description element styling for superset

---

app/frontend/src/elm/Component/Main/MainComponent.elm
app/frontend/src/elm/Component/Main/Page/Resource/Delegate.elm
app/frontend/src/elm/Component/Main/Page/Resource/Stake.elm
app/frontend/src/elm/Component/Main/Page/Resource/Undelegate.elm
app/frontend/src/elm/Component/Main/Page/Resource/Unstake.elm
app/frontend/src/elm/Component/Main/Sidebar.elm
app/frontend/src/elm/Data/Action.elm
app/frontend/src/elm/Translation.elm
app/frontend/src/elm/Util/WalletDecoder.elm
test/frontend/elm/Test/Component/Main/MainComponent.elm

Add the notification of delegatebw

---

app/frontend/src/elm/Component/Main/MainComponent.elm
app/frontend/src/elm/Component/Main/Page/Rammarket.elm
app/frontend/src/elm/Data/Action.elm

Tests and notifications are added in next PR

Ram finalize

---

app/frontend/src/elm/Component/Main/Page/Resource.elm
app/frontend/src/elm/Component/Main/Page/Resource/Delegate.elm
app/frontend/src/elm/Component/Main/Page/Resource/Stake.elm
app/frontend/src/elm/Component/Main/Page/Resource/Unstake.elm
app/frontend/src/elm/Component/Main/Page/Transfer.elm
app/frontend/src/elm/Data/Action.elm
app/frontend/src/elm/Util/Formatter.elm
app/frontend/src/elm/Util/Validation.elm
test/frontend/elm/Test/Component/Main/Page/Resource/Delegate.elm
test/frontend/elm/Test/Component/Main/Page/Resource/Stake.elm
test/frontend/elm/Test/Util/Formatter.elm

modal 부분은 undelegate 구현하면서 진행할 예정입니다.

Implement the Delegate tab

---

README.md

@basakkang  님과 제가 fe를 따로 빌드하는걸 몰라서 매우 느린 환경에서 개발하고 있었네요.
다음 분을 위해서 조금 더 자세하게 설명을 적었습니다.

add detail description for running process to README.md(step by)

---

app/frontend/src/elm/Component/Main/Page/Resource.elm
app/frontend/src/elm/Component/Main/Page/Resource/Delegate.elm
app/frontend/src/elm/Component/Main/Page/Resource/Modal/DelegateList.elm
app/frontend/src/elm/Component/Main/Page/Resource/Undelegate.elm
app/frontend/src/elm/Data/Table.elm
app/frontend/src/elm/Translation.elm

Undelegate 구현했습니다.
QA 이전 기준으로 기능 개발 완료했습니다.
테스트는 TODO로 남겨둡니다.

Implement Undelegate

---

app/views/layouts/root.html.erb

for anti flicking before css loaded
-----------------------------------------------
스타일시트가 하단에 있을때 가끔 스타일없이 로딩되는(흰색 배경에 검은색 글씨) 컨텐트가 생기지 않게 처리.

style element send to top

---

app/frontend/src/image/icon-refresh.svg
app/frontend/src/stylesheets/button.scss
app/frontend/src/stylesheets/layout.scss
app/frontend/src/stylesheets/main.index.scss
app/frontend/src/stylesheets/main.join.scss

@sinhyeok-cp
스타일시트 반영해 두었습니다.
데모 URL은 아래와 같습니다.
https://jdrunken.github.io/ui.eoshub/join-process.html
https://jdrunken.github.io/ui.eoshub/join-process-ok.html

renewal join process

---

app/frontend/src/stylesheets/main.ram-market.scss

@Heejaejoo 
램마켓 UI 변경됐습니다.
변경되는 html template는 아래 주소를 참조해 주세요.
https://github.com/jDrunken/ui.eoshub/commit/c60fde14dbd9f7ce4366a0f8f5e5660577e12682?diff=split#diff-fe1f41eb1d862bed18e08150046c8587
데모 html
https://jdrunken.github.io/ui.eoshub/ram-market.html

modify ram market ui

---

README.md

투표 페이지 정보수집에 필요한 레디스와 사이드킥에 대한 설정 및 설치방법을 추가.

add install and run redis & sidekiq

---

app/admin/products.rb
app/controllers/application_controller.rb
app/views/admin/admin_users/confirmations/new.html.erb

계정 생성 상품의 이름, 가격, 활성화 여부 등을 관리할 수 있는 어드민 페이지 추가

Add product admin page

---

app/frontend/src/stylesheets/main.search.scss

[qa 반영]
@basakkang 
메모를 메모답게 보이게.
정윤님 체크받고 올립니다.

search memo button attention adjustment

---

app/frontend/src/elm/Component/Main/MainComponent.elm
app/frontend/src/elm/Component/Main/Page/Index.elm
app/frontend/src/elm/Translation.elm
test/frontend/elm/Test/Component/Main/MainComponent.elm

[QA 반영] 메인 페이지 순서변경, 번역 추가, 댑 삭제

Remove dapp category and add the translation of manage resource

---

app/frontend/src/elm/Component/Main/Page/Rammarket.elm
app/frontend/src/elm/Component/Main/Page/Resource/Delegate.elm
app/frontend/src/elm/Component/Main/Page/Resource/Stake.elm
app/frontend/src/elm/Component/Main/Page/Resource/Undelegate.elm
app/frontend/src/elm/Component/Main/Page/Resource/Unstake.elm
app/frontend/src/elm/Component/Main/Page/Transfer.elm
app/frontend/src/elm/Component/Main/Sidebar.elm
app/frontend/src/elm/Util/Validation.elm
test/frontend/elm/Test/Component/Main/Page/Resource/Delegate.elm
test/frontend/elm/Test/Component/Main/Page/Resource/Undelegate.elm
test/frontend/elm/Test/Component/Main/Page/Transfer.elm
test/frontend/elm/Test/Util/Validation.elm

This PR is first part of 1st QA.
Also, remove the nova tab on sidebar and the dapps navigation field.

Implement account existence check.

---

config/initializers/sidekiq.rb
config/schedule.yml

This change will delete all existing cron jobs on remote redis server.

Modify sidekiq cron job settings.

---

.travis.yml
app/frontend/src/elm/Component/Main/Page/Rammarket.elm
app/frontend/src/elm/Component/Main/Page/Resource.elm
app/frontend/src/elm/Component/Main/Page/Resource/Delegate.elm
app/frontend/src/elm/Component/Main/Page/Resource/Stake.elm
app/frontend/src/elm/Component/Main/Page/Resource/Undelegate.elm
app/frontend/src/elm/Component/Main/Page/Resource/Unstake.elm
app/frontend/src/elm/Component/Main/Page/Search.elm
app/frontend/src/elm/Component/Main/Page/Vote.elm
app/frontend/src/elm/Component/Main/Sidebar.elm
app/frontend/src/elm/Data/Account.elm
app/frontend/src/elm/Util/Formatter.elm
app/frontend/src/stylesheets/aside.scss
test/frontend/elm/Test/Data/Account.elm
test/frontend/elm/Test/Util/Formatter.elm

리펀딩 time 계산 추가
resource 상태 color 추가. color 상태 비교가 필요해서 color 리턴 타입을 String 에서 Int로 변경.
기획 요청에 따라 time 포맷 변경

Index page/qa

---

app/frontend/src/elm/Component/Main/MainComponent.elm
app/frontend/src/elm/Component/Main/Page/Rammarket.elm
app/frontend/src/elm/Component/Main/Page/Vote.elm
app/frontend/src/js/index.js
test/frontend/elm/Test/Component/Main/Page/Rammarket.elm

Including changes of rammarket page in https://docs.google.com/spreadsheets/d/128WJPnhfOqHjnchEyjZDpdzAqJrdDYy5efFpW1KIbPI/edit#gid=0
Also, add restrictions to the vote page by disabling buttons.

Vote/Rammarket QA

---

app/frontend/src/stylesheets/main.join.scss
app/frontend/src/stylesheets/main.vote.scss

@sinhyeok-cp 
가입완료페이지의 스타일링 처리 추가되었습니다.
@Heejaejoo 
투표한 bp bi 처리 되어있습니다.

modify join & proxy vote

---

app/controllers/users_controller.rb
app/models/user.rb
config/locales/controllers/en.yml
config/locales/controllers/ko.yml
db/migrate/20181009133147_add_ip_address_to_user.rb
db/schema.rb
deploy/alpha/nginx.conf
deploy/production/nginx.conf
test/fixtures/users.yml
test/models/user_test.rb

동일한 ip로 최대 3회까지 계정생성 이벤트에 참여할 수 있도록

Can not participate in the event more than 3 times with the same IP address

---

app/frontend/src/elm/Component/Main/Page/Search.elm
app/frontend/src/elm/Translation.elm
test/frontend/elm/Test/Component/Main/Page/Search.elm

Search 페이지 수정된 ui에 맞춰 stake detail 정보 추가하였습니다.
test는 다음 PR로 올리도록 하겠습니다.

Implement staked details

---

Gemfile
Gemfile.lock

See https://devcenter.heroku.com/changelog-items/1437 for details.

Update sprocket version to resolve vulnerability issue.

---

app/frontend/src/elm/Component/Main/Sidebar.elm
app/frontend/src/elm/Translation.elm
test/frontend/elm/Test/Component/Main/Sidebar.elm

리소스 상태에 따른 Transaction 구분 text 추가

Add transaction status texts

---

app/frontend/src/elm/Component/Main/Sidebar.elm

1. onClick to onMouseEnter - Over
2. Apply url change to "보관토큰관리하기"

user interface QA.

---

deploy/cors.conf
deploy/production/nginx.conf

https://gist.github.com/algal/5480916 참고

Enhance nginx.conf for production env

---

app/frontend/src/elm/Component/Account/Page/Create.elm
app/frontend/src/elm/Component/Account/Page/EventCreation.elm
app/frontend/src/elm/Component/Account/Page/WaitPayment.elm
app/frontend/src/elm/Component/Main/MainComponent.elm
app/frontend/src/elm/Component/Main/Page/Index.elm
app/frontend/src/elm/Translation.elm
app/frontend/src/elm/View/Notification.elm

+@, 
1. Add route to notification when transaction successful.

Add english and chinese link of Dapp Contest

---

app/frontend/src/stylesheets/common.popup.scss
app/frontend/src/stylesheets/layout.scss
app/frontend/src/stylesheets/main.search.scss
app/frontend/src/stylesheets/main.transfer.scss

- 공개 키 검색의 개별 계정 마우스 커서가 링크임을 명시하도록 변경함 
커서를 올렸을때 인터랙션이 있게끔 변경함
- 팝업에서 제목과 input field의 바깥 여백이 없던 문제를 수정함
- 스크롤바를 항시 노출시켜 레이아웃을 고정되어 보이게 처리함
- 팝업의 모달레이어가 sidebar fold에 따라서 닫히거나 닫히지 않던 문제를 수정함
- 전송하기의 input height가 브라우저에 따라 달라지는 문제를 수정 처리

hotfix about design 

---

app/assets/stylesheets/popup_payment.scss
app/frontend/src/stylesheets/common.popup.scss
app/frontend/src/stylesheets/payment.popup.scss
app/frontend/src/stylesheets/style.scss

Complete separation to popup view asset (elm / ruby)

---

app/controllers/concerns/eos_account.rb
app/controllers/products_controller.rb
config/urls.yml
test/controllers/concerns/eos_account_test.rb

and disable event if the balance is smaller than 1 EOS

Check balance of event account

---

app/controllers/orders_controller.rb

로컬환경에서는 사실상 결제 테스트가 불가하지만 가상계좌 발급완료시 보여지는 팝업창을 테스트할 필요가 있어서 development 환경에서만 실제 결제와 상관없이 결제 요청시 가상계좌 발급완료 팝업이 바로 보이도록

Enable local payment test until issuing virtual account

---

app/frontend/src/elm/Component/Main/MainComponent.elm
app/frontend/src/js/index.js
app/workers/producer_stat_cron_worker.rb

Also, let producer stat cron job fetch all remaining data from block chain.

Elaborate wallet synchronization.

---

README.md
app/assets/stylesheets/popup_payment.scss
app/frontend/src/elm/Component/Main/Page/Rammarket.elm
app/frontend/src/elm/Component/Main/Page/Transfer.elm
app/frontend/src/stylesheets/button.scss
app/frontend/src/stylesheets/common.popup.scss
app/frontend/src/stylesheets/layout.scss
app/frontend/src/stylesheets/main.ram-market.scss
app/frontend/src/stylesheets/main.resource.scss
app/frontend/src/stylesheets/main.vote.scss
test/frontend/elm/Test/Component/Main/Page/Rammarket.elm

-   emphasis BP name, add to space for align
<https://docs.google.com/spreadsheets/d/1XDRNKvQsdVpuYbc9cBMJEqWXIxoX0q7P9uCTaEhCpkw/edit#gid=0>
-   fix rammarket UI
-   change vote page UI
-   tab button text color changed
-   add element for token counter
-   border width matching as intended
-   add interaction to loading button in search page
-   change for sidekiq running commmand - readme.md

modify to eoshub second launching

---

app/frontend/src/elm/Translation.elm
test/frontend/elm/Test/Component/Main/Page/Resource/Delegate.elm

@한재원님의 요청에 따라 번역이 필요없는 한글 워딩 변경했습니다.
11/7 eoshub 슬랙채널의 **단순 워딩 수정 요청사항.key** 참고

Edit Korean words

---

app/frontend/src/elm/Component/Main/Page/Search.elm

액션리스트 더보기 버튼에 loading 표시 추가, 총 갯수, 현재 갯수 표시 추가

Search loading

---

app/frontend/src/elm/Component/Main/Page/Search.elm
app/frontend/src/stylesheets/main.search.scss

Color asset

---

app/frontend/src/elm/Component/Account/Page/EventCreation.elm

Reverts EOSYS-io/eoshub.io#310

Revert "Add banner in EventCreation"

---

app/frontend/src/elm/Component/Main/Page/Index.elm
app/frontend/src/elm/Translation.elm

Reverts EOSYS-io/eoshub.io#309

Revert "Add additional translations"

---

app/frontend/src/elm/Component/Account/Page/EventCreation.elm

Reverts EOSYS-io/eoshub.io#312

Revert "Revert "Add banner in EventCreation""

---

app/frontend/src/elm/Component/Main/Page/Index.elm
app/frontend/src/elm/Translation.elm

Reverts EOSYS-io/eoshub.io#313

Revert "Revert "Add additional translations""

---

app/frontend/src/elm/Component/Account/AccountComponent.elm
app/frontend/src/elm/Component/Account/Page/Create.elm
app/frontend/src/elm/Component/Account/Page/Created.elm
app/frontend/src/elm/Component/Main/MainComponent.elm
app/frontend/src/elm/Component/Main/Page/Index.elm
app/frontend/src/elm/Component/Main/Sidebar.elm
app/frontend/src/elm/Data/Json.elm
app/frontend/src/elm/Translation.elm
app/frontend/src/stylesheets/common.popup.scss
app/frontend/src/stylesheets/main.join.scss
test/frontend/elm/Test/Component/Account/AccountComponent.elm

isEvent 에 따라 모든 view가 컨트롤 되도록 수정.
TODO 1. isAnnouncement flag 서버 작업
TODO 2. isAnnouncementCached flag 브라우저 cache 작업

Control event at admin

---

app/frontend/src/elm/Translation.elm

공지 문구 (11월 13일 재시작 내용으로) 수정 . master에 직접 반영.

Change announcement to restart event

---

app/frontend/src/elm/Translation.elm

Change announcement - event end

---

app/frontend/src/elm/Component/Main/MainComponent.elm
app/frontend/src/elm/Component/Main/Page/ChangeKey.elm
app/frontend/src/elm/Component/Main/Page/NewAccount.elm
app/frontend/src/elm/Component/Main/Page/Rammarket.elm
app/frontend/src/elm/Component/Main/Page/Resource/Delegate.elm
app/frontend/src/elm/Component/Main/Page/Resource/Stake.elm
app/frontend/src/elm/Component/Main/Page/Resource/Undelegate.elm
app/frontend/src/elm/Component/Main/Page/Resource/Unstake.elm
app/frontend/src/elm/Component/Main/Page/Search.elm
app/frontend/src/elm/Component/Main/Page/Transfer.elm
app/frontend/src/elm/Component/Main/Page/Vote.elm
app/frontend/src/elm/Component/Main/Sidebar.elm
app/frontend/src/elm/Data/Account.elm
app/frontend/src/elm/Data/Action.elm
app/frontend/src/elm/Data/Common.elm
app/frontend/src/elm/Route.elm
app/frontend/src/elm/Translation.elm
app/frontend/src/elm/Util/WalletDecoder.elm
test/frontend/elm/Test/Component/Main/Page/NewAccount.elm
test/frontend/elm/Test/Data/Account.elm
test/frontend/elm/Test/Data/Common.elm

Implement new account

---

app/frontend/src/stylesheets/main.account.scss
app/views/layouts/root.html.erb

@Heejaejoo 스타일과 meta 정보 수정했습니다.

resetting style for container box

---

app/frontend/src/elm/Component/Main/MainComponent.elm
app/frontend/src/elm/Component/Main/Page/Index.elm
test/frontend/elm/Test/Component/Main/MainComponent.elm

Index banner rolling하는 코드를 js에서 elm으로 변환했습니다.

Convert the banner's action code from js to elm

---

Gemfile
Gemfile.lock

To resolve the security issue, upgrate rack to over 2.0.6.

Update rack to 2.0.6.

---

app/frontend/src/elm/Component/Account/AccountComponent.elm
app/frontend/src/elm/Component/Account/Page/Create.elm
app/frontend/src/elm/Component/Account/Page/Created.elm
app/frontend/src/elm/Component/Account/Page/EventCreation.elm
app/frontend/src/elm/Component/Account/Page/WaitPayment.elm
app/frontend/src/elm/Component/Main/Page/Index.elm
app/frontend/src/elm/Component/Main/Page/NewAccount.elm
app/frontend/src/elm/Component/Main/Page/Rammarket.elm
app/frontend/src/elm/Component/Main/Page/Resource/Stake.elm
app/frontend/src/elm/Component/Main/Page/Search.elm
app/frontend/src/elm/Component/Main/Page/SearchKey.elm
app/frontend/src/elm/Component/Main/Sidebar.elm
app/frontend/src/elm/Data/Action.elm
app/frontend/src/elm/Data/Table.elm
app/frontend/src/elm/Route.elm
app/frontend/src/js/TradingView/loader.js

1. Clean up code.
Two major lint warnings are not fixed yet, which are TODO and Single record.
2. Apply default tradingview chart theme "Dark" and remove overrides.
3. Disable confirm button on new page when the user is not logged in.

Fix miscellaneous issues.

---

app/frontend/src/elm/Component/Main/Page/ChangeKey.elm
app/frontend/src/elm/Component/Main/Page/NewAccount.elm
app/frontend/src/elm/Translation.elm

Change translation

---

app/frontend/src/elm/Component/Main/Page/Rammarket.elm
app/frontend/src/elm/Component/Main/Page/Resource/Modal/DelegateList.elm
app/frontend/src/elm/Component/Main/Page/Resource/Stake.elm
app/frontend/src/elm/Component/Main/Page/Transfer.elm
app/frontend/src/elm/Component/Main/Page/Vote.elm
app/frontend/src/elm/Translation.elm

토큰 목록 팝업 검색창에서 엔터키 누르면 새로고침 되는 현상이 발생해서 form에 onSubmit 추가했습니다.
onSubmit의 동작은 input 태그의 onInput과 동일합니다.
검색 버튼도 현재로선 의미 없어서 추후 변경 예정.

Fix token list refresh issue

---

deploy/alpha/nginx.conf
deploy/production/nginx.conf

nginx에서 eos[s]can.io를 redirection.

Redirection eos[s]can.io in nginx

---

app/frontend/src/elm/Component/Main/MainComponent.elm
app/frontend/src/elm/Component/Main/Page/Index.elm
app/frontend/src/elm/Component/Main/Page/Vote.elm
app/frontend/src/elm/Data/Json.elm
app/frontend/src/elm/Translation.elm
app/frontend/src/js/constant.js
app/frontend/src/js/index.js
app/frontend/src/stylesheets/common.popup.scss
app/frontend/src/stylesheets/main.vote.scss

1. bp list search button deletion and retouching magnify-object in search input field
2. add time limiter and modified close button shape in notice popup template
@basakkang 타임 리미터 설정과 닫기버튼 개발 부탁드립니다.
요건 : https://docs.google.com/spreadsheets/d/1wYG_6ZE4APbhSUwgACmigEeU6yb7gbhTlnEE5qX5rzw/edit#gid=0
UI 참조 : https://jdrunken.github.io/ui.eoshub/index-view.html
git diff : https://github.com/jDrunken/ui.eoshub/commit/7f729eacddc435ae00d65d28ead24f27cbc66778#diff-f7427682c466f7a14a80dd455be785a4R160

modify 2 case

---

deploy/alpha/nginx.conf
deploy/production/nginx.conf

재원님의 요청에 따라 회사 외부에서도 admin page 접속 가능하도록 룰 변경합니다.

Remove ip addr regulation of admin page

---

app/frontend/src/elm/Data/Account.elm

Fix account decoder bug
